const options = {
    board: {
        width: 10,
        height: 10,
        fieldSize: 50,
    },
    probability: 100,
    borders: {
        borderTop: true,
        borderBottom: true,
        borderLeft: true,
        borderRight: true,
    },
    fractionNeighbors: true,
    timeInterval: 200,
    tribesNumber: 1,
    innerBorders: false,
    subtractGenerating: true,
    showFullColor: false,
    gaussRange: 20,
    underpopulation: 0.1,
    overpopulation: 0.6,
    minDeadCell: 0.1,
    maxDeadCell: 0.7,
}