const options = {
    board: {
        width: 10,
        height: 10,
        fieldSize: 50,
    },
    probability: 100,
    borders: {
        borderTop: true,
        borderBottom: true,
        borderLeft: true,
        borderRight: true,
    },
    fractionNeighbors: true,
    timeInterval: 200,
    tribesNumber: 1,
    innerBorders: false,
    subtractGenerating: true,
    showFullColor: true,
    gaussRange: 50,
    underpopulation: 1,
    overpopulation: 4,
    minDeadCell: 2,
    maxDeadCell: 3,
}