const testBoards = [
    {
        board: {
            width: 10,
            height: 10,
            fieldSize: 50,
        },
        probability: 0,
        borders: {
            borderTop: true,
            borderBottom: true,
            borderLeft: true,
            borderRight: true,
        },
        fractionNeighbors: true,
        timeInterval: 200,
        tribesNumber: 1,
        innerBorders: false,
        subtractGenerating: true,
        showFullColor: false,
        gaussRange: 20,
        massOfTribe: 5,
        underpopulation: 0.3,
        overpopulation: 0.6,
        minDeadCell: 0.45,
        maxDeadCell: 0.7,
        toManyOtherTribes: 0.3,
        setBlock: false,
        setDead: false,
        setAlive: false,
        wholeColumn: false,
        wholeRow: false,
        mouseDown: false,
        blockIntensity: 50,
        flashing: true,
        disappearsAfter: 10,
        appearsAfter: 10,
        cells: [
            {
                type: "alive",
                positions: [
                    {x: 9, y: 0},
                    {x: 0, y: 7}
                ],
                life: 1.0
            },
            {
                type: "block",
                positions: [
                    {x: 2, y: 0},
                    {x: 3, y: 0},
                    {x: 7, y: 0},
                    {x: 2, y: 1},
                    {x: 3, y: 1},
                    {x: 7, y: 1},
                    {x: 0, y: 2},
                    {x: 1, y: 2},
                    {x: 2, y: 2},
                    {x: 3, y: 2},
                    {x: 4, y: 2},
                    {x: 5, y: 2},
                    {x: 6, y: 2},
                    {x: 7, y: 2},
                    {x: 8, y: 2},
                    {x: 9, y: 2},
                    {x: 0, y: 3},
                    {x: 1, y: 3},
                    {x: 2, y: 3},
                    {x: 3, y: 3},
                    {x: 4, y: 3},
                    {x: 5, y: 3},
                    {x: 6, y: 3},
                    {x: 7, y: 3},
                    {x: 8, y: 3},
                    {x: 9, y: 3},
                    {x: 0, y: 4},
                    {x: 1, y: 4},
                    {x: 2, y: 4},
                    {x: 3, y: 4},
                    {x: 4, y: 4},
                    {x: 5, y: 4},
                    {x: 6, y: 4},
                    {x: 7, y: 4},
                    {x: 8, y: 4},
                    {x: 9, y: 4},
                    {x: 2, y: 5},
                    {x: 3, y: 5},
                    {x: 7, y: 5},
                    {x: 2, y: 6},
                    {x: 3, y: 6},
                    {x: 7, y: 6},
                    {x: 2, y: 7},
                    {x: 3, y: 7},
                    {x: 7, y: 7},
                    {x: 0, y: 8},
                    {x: 1, y: 8},
                    {x: 2, y: 8},
                    {x: 3, y: 8},
                    {x: 4, y: 8},
                    {x: 5, y: 8},
                    {x: 6, y: 8},
                    {x: 7, y: 8},
                    {x: 8, y: 8},
                    {x: 9, y: 8},
                    {x: 2, y: 9},
                    {x: 3, y: 9},
                    {x: 7, y: 9},
                ],
                blockIntensity: 0.5,
                flashing: true,
                disappearsAfter: 10,
                appearsAfter: 10,
                counter: 0
            }
        ]
    }
]